import { cx } from "@utils/tools";
import Head from "next/head";

export const MainLayout: IComponent = ({ children }) => {
  return (
    <div
      className={cx("w-full min-h-screen h-full font-serif")}
      style={{ fontFamily: "Manrope" }}
    >
      <div className="w-full h-full transition-all">
        <Head>
          <title>Zuni</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-full h-full bg-cover bg-center bg-default">
          {children}
        </div>
      </div>
    </div>
  );
};
